apiVersion: v1
kind: Service
metadata:
  name: ovpn0
  namespace: ovpn
  labels:
    app: ovpn0
spec:
  ports:
    - port: 1194
      targetPort: 1194
      nodePort: 31304
      protocol: UDP
      name: openvpn
  selector:
    app: ovpn0
  type: NodePort
